/** @type {import('cz-git').UserConfig} */
export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      ['feat', 'fix', 'docs', 'style', 'refactor', 'perf', 'test', 'chore', 'revert', 'build', 'ci'],
    ],
    'subject-max-length': [2, 'always', 100],
  },
  prompt: {
    alias: { fd: 'docs: fix typos' },
    messages: {
      type: '选择提交类型:',
      scope: '选择影响范围 (可选):',
      customScope: '输入自定义范围:',
      subject: '填写简短描述:\n',
      body: '填写详细描述 (可选，按回车跳过):\n',
      breaking: '列出破坏性变更 (可选，按回车跳过):\n',
      footerPrefixesSelect: '选择关联 issue 前缀 (可选):',
      customFooterPrefix: '输入自定义 issue 前缀:',
      footer: '列出关联 issue (可选，例如: #31, #34):\n',
      generatingByAI: 'AI 生成提交信息中...',
      generatedSelectByAI: '选择 AI 生成的提交信息:',
      confirmCommit: '确认提交?',
    },
    types: [
      { value: 'feat',     name: 'feat:     ✨  新功能',         emoji: ':sparkles:' },
      { value: 'fix',      name: 'fix:      🐛  修复 bug',       emoji: ':bug:' },
      { value: 'refactor', name: 'refactor: ♻️   代码重构',       emoji: ':recycle:' },
      { value: 'style',    name: 'style:    💄  样式/格式调整',   emoji: ':lipstick:' },
      { value: 'build',    name: 'build:    👷  构建流程变更',    emoji: ':construction_worker:' },
      { value: 'perf',     name: 'perf:     ⚡️  性能优化',        emoji: ':zap:' },
      { value: 'test',     name: 'test:     ✅  添加/修改测试',   emoji: ':white_check_mark:' },
      { value: 'docs',     name: 'docs:     📝  文档变更',        emoji: ':memo:' },
      { value: 'chore',    name: 'chore:    🔨  其他杂项变更',   emoji: ':hammer:' },
      { value: 'revert',   name: 'revert:   ⏪️  回滚提交',        emoji: ':rewind:' },
      { value: 'ci',       name: 'ci:       🎡  CI 配置变更',     emoji: ':ferris_wheel:' },
    ],
    useEmoji: true,
    emojiAlign: 'center',
    themeColorCode: '',
    scopes: [
      { value: 'ui',        name: 'ui:        前端界面 (Vue/CSS)' },
      { value: 'overlay',   name: 'overlay:   绘制覆盖层逻辑' },
      { value: 'shortcut',  name: 'shortcut:  全局快捷键' },
      { value: 'tray',      name: 'tray:      系统托盘' },
      { value: 'clipboard', name: 'clipboard: 截图/剪贴板' },
      { value: 'config',    name: 'config:    应用配置' },
      { value: 'i18n',      name: 'i18n:      国际化' },
      { value: 'ci',        name: 'ci:        CI/CD 流程' },
      { value: 'deps',      name: 'deps:      依赖更新' },
    ],
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlign: 'bottom',
    customScopesAlias: 'custom',
    emptyScopesAlias: 'empty',
    upperCaseSubject: false,
    markBreakingChangeMode: false,
    allowBreakingChanges: ['feat', 'fix'],
    breaklineNumber: 100,
    breaklineChar: '|',
    skipQuestions: ['body', 'breaking'],
    issuePrefixes: [{ value: 'closed', name: 'closed: ISSUES 已关闭' }],
    customIssuePrefixAlign: 'top',
    emptyIssuePrefixAlias: 'skip',
    customIssuePrefixAlias: 'custom',
    allowCustomIssuePrefix: true,
    allowEmptyIssuePrefix: true,
    confirmColorize: true,
    maxHeaderLength: Infinity,
    maxSubjectLength: Infinity,
    minSubjectLength: 0,
    scopeOverrides: undefined,
    defaultBody: '',
    defaultIssues: '',
    defaultScope: '',
    defaultSubject: '',
  },
}
